import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "./components/Header";
import Footer from "./components/Footer";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { CartProvider } from "./cart/context/CartContext";
import { ClerkProvider, SignedIn, SignedOut, SignInButton, UserButton } from "@clerk/clerk-react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Comforty",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
            
      <body className={inter.className}>
        <CartProvider>
      <Header/>
      <Toaster/>
        {children}
      <Footer/>
        </CartProvider>
      </body>
    </html>

  );
}
