import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "./components/Header";
import Footer from "./components/Footer";
import "./globals.css";
import { CartProvider } from "./cart/context/CartContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Comforty",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CartProvider>
      <Navbar/>
        {children}
      <Footer/>
      </CartProvider>
      </body>
    </html>
  );
}
